repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^.*/alembic/versions/.*\.py$
      - id: ruff-format
        exclude: ^.*/alembic/versions/.*\.py$
        args: [ "--config=pyproject.toml" ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^.*/alembic/versions/.*\.py$