"""add_user_id_to_collection_and_llm

Revision ID: 4e9496fc768b
Revises: e7f8a9b0c1d2
Create Date: 2026-05-09 15:46:28.903222

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9496fc768b'
down_revision: Union[str, Sequence[str], None] = 'e7f8a9b0c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'agent', 'user', ['user_id'], ['id'])
    op.add_column('collection', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'collection', 'user', ['user_id'], ['id'])
    op.add_column('llm', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'llm', 'user', ['user_id'], ['id'])
    op.drop_index(op.f("idx_message_conversation_created_at"), table_name="message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_message_conversation_created_at'), 'message', ['conversation_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'llm', type_='foreignkey')
    op.drop_column('llm', 'user_id')
    op.drop_constraint(None, 'collection', type_='foreignkey')
    op.drop_column('collection', 'user_id')
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.drop_column('agent', 'user_id')
    # ### end Alembic commands ###
