"""adjust unique constraint in collection

Revision ID: 5b429f57fab6
Revises: 4e9496fc768b
Create Date: 2026-05-09 17:32:08.381801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b429f57fab6'
down_revision: Union[str, Sequence[str], None] = '4e9496fc768b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collection_name_key'), 'collection', type_='unique')
    op.create_unique_constraint('uq_collection_name_user', 'collection', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_collection_name_user', 'collection', type_='unique')
    op.create_unique_constraint(op.f('collection_name_key'), 'collection', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
